# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smop_solve_bmop <- function(A, b, delta, options = NULL, x0 = NULL) {
    .Call(`_smop_smop_solve_bmop`, A, b, delta, options, x0)
}

smop_solve_lasso <- function(A, b, lambda, options = NULL, x0 = NULL) {
    .Call(`_smop_smop_solve_lasso`, A, b, lambda, options, x0)
}

smop_version_cpp <- function() {
    .Call(`_smop_smop_version_cpp`)
}

