// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// smop_solve_bmop
Rcpp::List smop_solve_bmop(Rcpp::NumericMatrix A, Rcpp::NumericVector b, double delta, Rcpp::Nullable<Rcpp::List> options, Rcpp::Nullable<Rcpp::NumericVector> x0);
RcppExport SEXP _smop_smop_solve_bmop(SEXP ASEXP, SEXP bSEXP, SEXP deltaSEXP, SEXP optionsSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(smop_solve_bmop(A, b, delta, options, x0));
    return rcpp_result_gen;
END_RCPP
}
// smop_solve_lasso
Rcpp::List smop_solve_lasso(Rcpp::NumericMatrix A, Rcpp::NumericVector b, double lambda, Rcpp::Nullable<Rcpp::List> options, Rcpp::Nullable<Rcpp::NumericVector> x0);
RcppExport SEXP _smop_smop_solve_lasso(SEXP ASEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP optionsSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(smop_solve_lasso(A, b, lambda, options, x0));
    return rcpp_result_gen;
END_RCPP
}
// smop_version_cpp
std::string smop_version_cpp();
RcppExport SEXP _smop_smop_version_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(smop_version_cpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smop_smop_solve_bmop", (DL_FUNC) &_smop_smop_solve_bmop, 5},
    {"_smop_smop_solve_lasso", (DL_FUNC) &_smop_smop_solve_lasso, 5},
    {"_smop_smop_version_cpp", (DL_FUNC) &_smop_smop_version_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_smop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
